--- # Install and enable apache
- hosts: all
  become: yes

  tasks:
  - name: install apache
    apt:
       name: apache2
       state: absent
  
  - name: start and enable apache service
    service:
       name: apache2
       state: started
       enabled: yes 
