--- # update all pakages
- hosts: all
  become: yes
  
  tasks:
  - name: run apt update
    apt:
       name: "*"
       state: latest

  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
       upgrade: dist

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
       update_cache: yes

  - name: restart system
    reboot:
       reboot_timeout: 3600

