--- # Create New User
- hosts: all
  become: yes
 
  tasks:
  - name: create new user
    user:
        name: docker
        password: xxxxx
        shell: /bin/bash
        groups: sudo, docker
        append: yes
        create_home: true
           
                
