--- # Create New User
- hosts: all
  become: yes
 
  tasks:
  - name: create new user
    user:
        name: docker
        password: $5$7DNlVjDbH2Oi29Fo$HPAHvlFnFco1XzvxgrZGfSYIvi1KSKcY2iNuRx9Pz75 
        shell: /bin/bash
        groups: sudo, docker
        append: yes
        create_home: true
           
                
