--- # debug module
- hosts: all
  become: yes

  tasks:
  - name: running a simple command
    shell: echo "echo command ran sucessfully!"
    register: code_1

  - name: printing variable with some msg
    debug:
         msg="{{ code_1.stdout }}"
    

--- # File Modules
- hosts: all
  become: yes
 
  tasks:
# create a file
  - name: create file on a remote server
    file:
        path: /home/ansible/users.txt
        state: touch
        mode: 755
        owner: ansible
    ignore_errors: True

# add block of lines to a file using blockinfile module
  - name: add block of lines to a file abc.txt
    blockinfile:
        path: /home/ansible/abc.txt
        block: |
         Hi this is a test!
         It will go to the end of the file.
# copy module: copy files/directoty from host to remote hosts
  - name: copy module
    copy:
        src: /home/ansible/ansible/test_file
        dest: /home/ansible/
        # force is optional; by default it is set to yes. yes=>it will replace the file if it exist. no=> it will not replace the file
        force: yes

# copy multiple files at once
  - name: copy multiple files
    copy: src=/home/ansible/ansible/test_folder/ dest=/home/ansible
    with_items:
          - file1
          - file2

# create new directory
  - name: create new directory
    file:
        path: /home/ansible/test_folder_2
        state: directory
        mode: 0755
        group: ansible
        owner: ansible

# create directory if it doesnt exist
  - name: check for existing directory
    stat:
        path: /home/ansible/test_folder
    register: test_folder

  - name: checcking if it's already existed
    debug:
         msg: "test_folder already existed"
    when: test_folder.stat.exists
 
  - name: create directory if it doesn't exist
    file:
        path: /home/ansible/test_folder
        state: directory
        mode: 0755
        group: ansible
        owner: ansible
    when: test_folder.stat.exists == false


# command module
  - name: run any linux/shell command
    command: rm -rf /home/ansible/test_folder_2
    tags:
        - remove
    ignore_errors: True

--- # Replace Module
- hosts: all
  become: yes
  tasks:
  - name: replace sam with sarah
    replace:
           path: /home/ansible/users.txt
           regexp: "sam"
           replace: "sarah"


--- # add user and group
- hosts: all
  become: yes
  tasks:

  - name: create a group
    group:
         name: test_group
  

# create user and assign test_group to a user
  - name: create user and assign user to test group
    user:
        name: sammy.quang
        group: test_group

